#!/bin/bash
# FILENAME:  file.sub


echo $CUDA_VISIBLE_DEVICES


python train_script.py \
  --epochs 10 \
  --batch_size 64 \
  --lr 0.001 \
  --num_masks 10 \
  --dropout_probs 0.3 0.7 \
  --num_groups 10 \
  --pruning_rate 0.5 0.8 0.95 \



# python train_script.py \
#   --epochs 10 \
#   --batch_size 64 \
#   --lr 0.001 \
#   --num_masks 10 \
#   --dropout_probs 0.2 0.7 \
#   --num_groups 10 \
#   --pruning_rate 0.4 0.5 0.8 \

# python train_script.py \
#   --epochs 10 \
#   --batch_size 64 \
#   --lr 0.001 \
#   --num_masks 10 \
#   --dropout_probs 0.2 0.7 \
#   --num_groups 10 \
#   --pruning_rate 0.2 0.4 0.7 \



# python train_script.py \
#   --epochs 10 \
#   --batch_size 64 \
#   --lr 0.001 \
#   --num_masks 10 \
#   --dropout_probs 0.2 0.7 \
#   --num_groups 10 \
#   --pruning_rate 0.1 0.3 0.7 \


