#!/bin/bash
# FILENAME:  file.sub


echo $CUDA_VISIBLE_DEVICES


  # python train_script.py \
  # --epochs 10 \
  # --batch_size 64 \
  # --lr 0.001 \
  # --num_masks 50 \
  # --dropout_probs 0.2 0.3 \
  # --num_groups 50 \
  # --pruning_rate 0.0 0.7 0.93 \

  # python train_script.py \
  # --epochs 10 \
  # --batch_size 64 \
  # --lr 0.001 \
  # --num_masks 25 \
  # --dropout_probs 0.2 0.3 \
  # --num_groups 25 \
  # --pruning_rate 0.0 0.7 0.93 \

  # python train_script.py \
  # --epochs 10 \
  # --batch_size 64 \
  # --lr 0.001 \
  # --num_masks 10 \
  # --dropout_probs 0.2 0.4 \
  # --num_groups 10 \
  # --pruning_rate 0.0 0.7 0.93 \

  # python train_script.py \
  # --epochs 10 \
  # --batch_size 64 \
  # --lr 0.001 \
  # --num_masks 5 \
  # --dropout_probs 0.3 0.4 \
  # --num_groups 5 \
  # --pruning_rate 0.0 0.7 0.93 \


  # python train_script.py \
  # --epochs 10 \
  # --batch_size 64 \
  # --lr 0.001 \
  # --num_masks 10 \
  # --dropout_probs 0.2 0.7 \
  # --num_groups 3 \
  # --pruning_rate 0.0 0.7 0.93 \


  # python train_script.py \
  # --epochs 10 \
  # --batch_size 64 \
  # --lr 0.001 \
  # --num_masks 5 \
  # --dropout_probs 0.2 0.5 \
  # --num_groups 5 \
  # --pruning_rate 0.0 0.7 0.93 \


  # python train_script.py \
  # --epochs 10 \
  # --batch_size 64 \
  # --lr 0.001 \
  # --num_masks 1 \
  # --dropout_probs 0.0 0.0 \
  # --num_groups 1 \
  # --pruning_rate 0.0 0.7 0.93 \

  #   python train_script_tuning.py \
  # --epochs 10 \
  # --batch_size 64 \
  # --lr 0.001 \
  # --num_masks 50 \
  # --dropout_probs 0.2 0.3 \
  # --num_groups 50 \
  # --pruning_rate 0.0 0.7 0.93 \


  # python train_script_tuning.py \
  # --epochs 10 \
  # --batch_size 64 \
  # --lr 0.001 \
  # --num_masks 25 \
  # --dropout_probs 0.2 0.3 \
  # --num_groups 25 \
  # --pruning_rate 0.0 0.7 0.93 \


  # python train_script_tuning.py \
  # --epochs 10 \
  # --batch_size 64 \
  # --lr 0.001 \
  # --num_masks 1 \
  # --dropout_probs 0.0 0.0 \
  # --num_groups 1 \
  # --pruning_rate 0.0 0.7 0.93 \

  python train_script_cifar.py --epochs 5 --batch_size 64 --lr 0.001  --num_masks 1  --dropout_probs 0.0 0.0 --num_groups 1 --pruning_rate 0.0 0.7 0.93 